// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwouwmhbqjpoiocykjac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3b3V3bWhicWpwb2lvY3lramFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjA5NjEsImV4cCI6MjA2NTU5Njk2MX0.FavBqXs01vMayJsddzQUSzkszKxUoDOhB-df_HLVbJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);